spring.application.name=mundialscore

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mundialscore_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA (AUTO-GENERA TABLAS)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs

# (Opcional) para evitar warning de open-in-view
spring.jpa.open-in-view=false
